 deploy-job:
    docker:
      - image: circleci/node:8
    working_directory: /home/circleci/repo
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: npm build && aws s3 cp ./build s3://kkipp-testing-circleci --recursive --include "*" --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master