version: 2
jobs:
  build-job:
    docker:
      - image: third774/testing-circleci:latest
    working_directory: /home/circleci/repo
    steps:
      - run:
          name: install deps and build
          command: git clone https://github.com/third774/testing-circleci.git . && npm i && npm run build

  deploy-job:
    docker:
      - image: third774/testing-circleci:latest
    working_directory: /home/circleci/repo
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: git clone https://github.com/third774/testing-circleci.git . && npm i && npm run build && aws s3 cp /home/circleci/repo/build s3://kkipp-testing-circleci --recursive --include "*" --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
          filters:
            tags:
              only: /.*/
      - deploy-job:
          requires:
            - build-job
          filters:
            tags:
              only: /^v.*$/
            branches:
              only: master